# Generated by Django 6.0.1 on 2026-01-08 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseNutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('unit', models.CharField(max_length=20)),
                ('daily_target', models.FloatField(help_text='Recommended daily intake.')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Ingredients, recipe, or notes.')),
                ('calories', models.PositiveIntegerField(help_text='Approximate calories per serving.')),
                ('preview_image', models.URLField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True, help_text='If True, this meal can be randomly assigned to other users.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(help_text='The user who added this meal. Null if system-provided.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_meals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=20)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_meals', to='planner.meal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'meal_type'],
                'unique_together': {('user', 'date', 'meal_type')},
            },
        ),
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(help_text='Amount of this nutrient in the meal.')),
                ('base_nutrient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meal_measurements', to='planner.basenutrient')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrients', to='planner.meal')),
            ],
            options={
                'unique_together': {('meal', 'base_nutrient')},
            },
        ),
    ]
