# Generated by Django 6.0.1 on 2026-01-08 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNutrientRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_target', models.FloatField(help_text='User-specific daily intake target.')),
                ('source', models.CharField(help_text="Source of this requirement (e.g. 'user_added', 'generated').", max_length=100)),
                ('base_nutrient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_requirements', to='planner.basenutrient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrient_requirements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Nutrient Requirement',
                'verbose_name_plural': 'User Nutrient Requirements',
                'unique_together': {('user', 'base_nutrient')},
            },
        ),
    ]
